// src/components/SmartImage.jsx — Style Eternal
// Manifest-driven responsive <picture>: serves the WebP variants generated by
// scripts/optimize-media.mjs with the original file as fallback. Falls back
// to a plain <img> for sources outside the manifest (external URLs, SVGs).

import React from "react";
import manifest from "../data/mediaManifest.json";

function buildSrcSet(entry) {
  const [fullWidth, ...smaller] = entry.widths;
  const parts = [`${entry.webp} ${fullWidth}w`];
  for (const w of smaller) {
    parts.push(`${entry.webp.replace(/\.webp$/, `-${w}.webp`)} ${w}w`);
  }
  return parts.join(", ");
}

export default function SmartImage({
  src,
  alt = "",
  sizes = "100vw",
  loading = "lazy",
  fetchPriority,
  decoding = "async",
  className = "",
  style,
  ...rest
}) {
  const entry = src ? manifest[src] : null;

  if (!entry) {
    return (
      <img
        src={src}
        alt={alt}
        loading={loading}
        decoding={decoding}
        {...(fetchPriority ? { fetchPriority } : {})}
        className={className}
        style={style}
        {...rest}
      />
    );
  }

  return (
    <picture>
      <source type="image/webp" srcSet={buildSrcSet(entry)} sizes={sizes} />
      <img
        src={src}
        alt={alt}
        loading={loading}
        decoding={decoding}
        {...(fetchPriority ? { fetchPriority } : {})}
        {...(entry.width && entry.height
          ? { width: entry.width, height: entry.height }
          : {})}
        className={className}
        style={style}
        {...rest}
      />
    </picture>
  );
}
