// src/utils/productMedia.js
//
// Single image/media convention helper.
//
// Convention (every product folder follows the same pattern):
//   /public/assets/products/<productSlug>/
//     - 01.jpg  (primary — WebP variants are generated by
//                scripts/optimize-media.mjs and served via SmartImage)
//     - 02.jpg  (optional)
//     - video.mp4 (optional)
//
// A product can either provide an explicit `images: []` array OR declare:
//   - imageFolder: "/assets/products/<slug>"  (or "/gallery/..." etc)
//   - imageCount: 3
//   - video: "/assets/products/<slug>/video.mp4" (optional)
//
// Convention paths resolve against the media manifest so the extension always
// matches a file that actually exists (a hardcoded ".webp" here once produced
// broken URLs for every convention-based product — the assets were .jpg).

import mediaManifest from "../data/mediaManifest.json";

const pad2 = (n) => String(n).padStart(2, "0");
const CONVENTION_EXTENSIONS = ["jpg", "webp", "jpeg", "png"];

function conventionPath(folder, index) {
  const stem = `${folder}/${pad2(index)}`;
  for (const ext of CONVENTION_EXTENSIONS) {
    const candidate = `${stem}.${ext}`;
    if (mediaManifest[candidate]) return candidate;
  }
  // Not in the manifest (new upload, external folder) — default to .jpg,
  // the catalog's actual asset format.
  return `${stem}.jpg`;
}

export function resolveProductImages(product) {
  if (!product) return [];

  // 1) Explicit images win (backwards compatible)
  if (Array.isArray(product.images) && product.images.length) {
    return product.images.filter(Boolean);
  }

  // 2) Convention-driven images
  const folder =
    product.imageFolder ||
    product.mediaFolder ||
    product.mediaBase ||
    (product.slug ? `/assets/products/${product.slug}` : null);

  const count =
    Number(product.imageCount || product.mediaCount || product.media?.imageCount || product.media?.images || 0) ||
    0;

  if (!folder || count <= 0) return [];

  return Array.from({ length: count }, (_, i) => conventionPath(folder, i + 1));
}

export function resolveProductVideo(product) {
  if (!product) return null;
  return (
    product.video ||
    product.videoSrc ||
    product.media?.video ||
    (product.slug ? `/assets/products/${product.slug}/video.mp4` : null)
  );
}
