-- ============================================================================
-- Style Eternal — Seed products from src/data/products.js
-- Generated by scripts/generate-products-seed.mjs — do not edit by hand.
--
-- Populates the products table (commerce subset) so the admin panel lists
-- and inline-edits every product. ON CONFLICT (slug) DO NOTHING keeps it
-- idempotent and never overwrites prices/stock an admin has already changed.
-- The storefront overlays price/stock/is_active from this table by slug.
-- ============================================================================

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('North Ward Tee — Black', 'north-ward-tee-black', 'Heavyweight oversized tee with back graphic. Washed for a broken-in feel from day one.', 65, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('North Ward Tee — Bone', 'north-ward-tee-bone', 'Heavyweight oversized tee with back graphic. The bone colorway.', 65, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('North Ward Hoodie — Black', 'north-ward-hoodie-black', 'Heavy French terry pullover. Oversized. Back graphic. Kangaroo pocket.', 145, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('North Ward Hoodie — Charcoal', 'north-ward-hoodie-charcoal', 'Heavy French terry pullover. Charcoal wash.', 145, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('North Ward Long Sleeve — Black', 'north-ward-longsleeve-black', 'Heavyweight long sleeve with sleeve print detail. Oversized fit.', 75, NULL, 100, 'long-sleeves', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('North Ward Crewneck — Black', 'north-ward-crewneck-black', 'Heavy crewneck with embroidered chest logo. Clean and minimal.', 125, NULL, 100, 'crewnecks', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Iron Bound Tee — Asphalt', 'iron-bound-tee-asphalt', 'Relaxed fit tee with front graphic print. Garment dyed.', 55, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Iron Bound Hoodie — Concrete', 'iron-bound-hoodie-concrete', 'Garment washed heavyweight hoodie. Front graphic. Relaxed drop shoulder.', 155, NULL, 150, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Essentials Tee — Black', 'essentials-tee-black', 'The daily uniform. Embroidered logo. Nothing extra.', 45, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Essentials Tee — Bone', 'essentials-tee-bone', 'The daily uniform in bone. Embroidered logo.', 45, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Essentials Hoodie — Black', 'essentials-hoodie-black', 'Everyday hoodie. Embroidered logo. Relaxed fit.', 120, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Essentials Sweatpant — Black', 'essentials-sweatpant-black', 'Tapered sweatpant. Side pockets. Elastic waist and cuffs.', 110, NULL, 100, 'bottoms', '[{"label":"28","stock":null},{"label":"30","stock":null},{"label":"32","stock":null},{"label":"34","stock":null},{"label":"36","stock":null},{"label":"38","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Legacy Varsity Jacket — Black/Gold', 'legacy-varsity-jacket', 'Wool and leather varsity jacket. Chenille patches. Satin lining.', 395, NULL, 50, 'outerwear', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Legacy Fitted Cap — Black', 'legacy-fitted-cap', 'Structured fitted cap with embroidered SE logo.', 48, NULL, 100, 'headwear', '[{"label":"OS","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Legacy Beanie — Black', 'legacy-beanie-black', 'Ribbed knit beanie with woven SE label.', 35, NULL, 100, 'headwear', '[{"label":"OS","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Survival Graphic Tee — Washed Black', 'survival-graphic-tee', 'Distressed finish graphic tee. Oversized. Heavy.', 70, NULL, 200, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Eternal Graphic Long Sleeve — Black', 'eternal-graphic-longsleeve', 'Multi-print long sleeve. Front, back, and sleeve graphics.', 80, NULL, 100, 'long-sleeves', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Utility Tote — Black', 'utility-tote-black', 'Heavy canvas tote with screenprinted logo. Internal pocket.', 40, NULL, 100, 'accessories', '[{"label":"OS","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Archive 001 Tee — Cement', 'archive-001-tee', 'First run tee from the original capsule. Archived.', 65, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Love Never Dies Tee — Washed Black', 'love-never-dies-tee', 'Oversized washed black tee. Skeleton graphic with ''Love Never Dies'' script and OOPS! speech bubble. Brought to you by Style Eternal.', 75, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '["/assets/products/love-never-dies-tee/01.jpg"]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Eternal Love Hoodie — Black', 'eternal-love-hoodie', 'All-over print hoodie. Skeleton carrying figure, red flames on sleeves, ''ETERNAL Love'' chest graphic. Another day, in another world, love is eternity.', 150, NULL, 50, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '["/assets/products/eternal-love-hoodie/01.jpg"]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Freedom for Minorities Hoodie — Washed Black', 'freedom-for-minorities-hoodie', 'Washed black heavyweight hoodie. ''Freedom for Minorities'' front graphic — raised fist, burning cruiser, handcuffs. We are human but born in different bodies.', 140, NULL, 75, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '["/assets/products/freedom-hoodie/01.jpg"]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Forbidden Love Hoodie — Black', 'forbidden-love-hoodie', 'Heavyweight black hoodie. ''Forbidden Love'' front graphic — skeleton embrace, broken hearts. Love is eternal, just like style.', 140, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '["/assets/products/forbidden-love-hoodie/01.jpg"]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('SE Worldwide Long Sleeve — Black', 'se-worldwide-longsleeve', 'All-over print long sleeve. SE crest front, ''Style Eternal EST. 2021'' medallion back, gold star graphics on sleeves. Worldwide representation.', 110, NULL, 100, 'long-sleeves', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '["/assets/products/se-worldwide-longsleeve/01.jpg"]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Eternal Flame Hoodie — Black', 'eternal-flame-hoodie', 'Anime-inspired figures with halos and pink/purple flames. 400gsm heavyweight fleece. The flame never dies.', 150, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Eternal Flame Circle Hoodie — Black', 'eternal-flame-circle-hoodie', 'Distressed circle medallion graphic on heavyweight fleece. The Eternal Flame emblem — forged in fire, worn forever.', 150, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Eternal Freedom Tee — Washed Black', 'eternal-freedom-tee', 'Split-panel angels, cityscape silhouettes, broken chains. 280gsm heavyweight cotton with garment wash.', 75, NULL, 100, 'tees', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.products (name, slug, description, price, compare_at_price, stock, category, variants, images, is_active)
VALUES ('Eternal Unity Hoodie — Black', 'eternal-unity-hoodie', 'Four hooded silhouettes, candles, roses. Unity graphic on heavyweight 400gsm fleece. Limited to 100 pieces.', 155, NULL, 100, 'hoodies', '[{"label":"S","stock":null},{"label":"M","stock":null},{"label":"L","stock":null},{"label":"XL","stock":null},{"label":"XXL","stock":null}]'::jsonb, '[]'::jsonb, true)
ON CONFLICT (slug) DO NOTHING;
